[tool.poetry]
name = "llm-pdf-qa-sample-app"
version = "0.1.0"
description = ""
authors = ["Han Lee <lee.hanchung@gmail.com>"]
readme = "README.md"
packages = [{include = "llm_pdf_qa_sample_app"}]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.8"
langchain = "^0.0.220"
chainlit = "^0.5.0"
tiktoken = "^0.4.0"
pdfplumber = "^0.9.0"
chromadb = "^0.3.26"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.274"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
